name: "donation-demo"

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - donation-demo-local
    volumes:
      - ./provision/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

#  healthcheck-wait:
#    image: busybox
#    container_name: healthcheck-wait
#    depends_on:
#      mysql:
#        condition: service_healthy
#
  api:
    build:
      context: ../../
      dockerfile: ./infra/docker/api.dockerfile
    ports:
      - "3001:3001"
    networks:
      - donation-demo-local
    env_file: ../../server-1/.env
    environment:
      DB_URI: "mysql://root:password@mysql:3306/donation"

  handler:
    build:
      context: ../../
      dockerfile: ./infra/docker/event-handler.dockerfile
    env_file: ../../server-1/.env
    environment:
      DB_URI: "mysql://root:password@mysql:3306/donation"
    networks:
      - donation-demo-local
#
#  client:
#    build:
#      context: ../../
#      dockerfile: ./infra/docker/client.dockerfile
#    environment:
#      CSPR_CLICK_APP_NAME: "Lottery Demo"
#      CSPR_CLICK_APP_ID: "cspr-lottery-demo"
#    networks:
#      - donation-demo-local
#    ports:
#      - 3000:80
#    depends_on:
#      - api
#      - handler

volumes:
  mysql-data:
    driver: local

networks:
  donation-demo-local: