name: "donation-demo"
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    hostname: donation-mysql
    networks:
      - donation-demo-local
    volumes:
      - ./provision/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  api:
    container_name: api
    build:
      context: ../../
      dockerfile: ./infra/docker/api.dockerfile
    ports:
      - "4000:4000"
    networks:
      - donation-demo-local
    env_file: ../../server/.env
    environment:
      DB_URI: "mysql://root:password@donation-mysql:3306/donation"

  handler:
    build:
      context: ../../
      dockerfile: ./infra/docker/event-handler.dockerfile
    env_file: ../../server/.env
    environment:
      DB_URI: "mysql://root:password@donation-mysql:3306/donation"
    networks:
      - donation-demo-local

  client:
    build:
      context: ../../
      dockerfile: ./infra/docker/client.dockerfile
    environment:
      DONATION_CONTRACT_PACKAGE_HASH: "ca0f4eedc84e03b6bc39ce664ef05dff00a96214194e706d50bfc43d84124035"
      DONATION_API_URL: "http://localhost:3001"
      CSPR_CLICK_APP_NAME: "Donation Demo"
      CSPR_CLICK_APP_ID: "csprclick-template"
      CSPR_LIVE_URL: "https://testnet.cspr.live"
      TRANSACTION_PAYMENT: "10000000000"
    networks:
      - donation-demo-local
    ports:
      - 3000:80
    depends_on:
      - api
      - handler

volumes:
  mysql-data:
    driver: local

networks:
  donation-demo-local: