name: "donation-demo"
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    hostname: donation-mysql
    networks:
      - donation-demo-local
    volumes:
      - ./provision/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: ../../
      dockerfile: ./infra/docker/api.dockerfile
    ports:
      - "4000:4000"
    env_file: ../../server/.env
    networks:
      - donation-demo-local
    depends_on:
      mysql:
        condition: service_healthy

  handler:
    build:
      context: ../../
      dockerfile: ./infra/docker/event-handler.dockerfile
    env_file: ../../server/.env
    networks:
      - donation-demo-local
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: ../../
      dockerfile: ./infra/docker/client.dockerfile
    environment:
      DONATION_CONTRACT_PACKAGE_HASH: "c447e9d334a710bc3e0a47cbea854c269e41637d7b9aa9d37a745596f651ed7a"
      DONATION_API_URL: "http://localhost:4000"
      CSPR_CLICK_APP_NAME: "Donation Demo"
      CSPR_CLICK_APP_ID: "csprclick-template"
      CSPR_CLICK_PROVIDERS: '["casper-wallet", "ledger", "metamask-snap"]'
      CSPR_LIVE_URL: "https://testnet.cspr.live"
      TRANSACTION_PAYMENT: "10000000000"
    networks:
      - donation-demo-local
    ports:
      - 3000:80

volumes:
  mysql-data:
    driver: local

networks:
  donation-demo-local: