blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question or discuss an idea
    url: https://t.me/CSPRDevelopers
    about: Ask your questions and discuss your ideas in Casper Developer group on Telegram

